// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PrimaryAggregatorService.Models.DataBases;

#nullable disable

namespace PrimaryAggregatorService.Migrations
{
    [DbContext(typeof(AggregatorContext))]
    [Migration("20230505203701_CREATE_FUNCTION_Delete_old_order")]
    partial class CREATE_FUNCTION_Delete_old_order
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PrimaryAggregatorService.Models.DataBases.OrderDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<short>("Duration")
                        .HasColumnType("smallint");

                    b.Property<bool>("IsBuyOrder")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Issued")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("LocationId")
                        .HasColumnType("bigint");

                    b.Property<int>("MinVolume")
                        .HasColumnType("integer");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("PackageDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<string>("Range")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SystemId")
                        .HasColumnType("integer");

                    b.Property<int>("TypeId")
                        .HasColumnType("integer");

                    b.Property<long>("VolumeRemain")
                        .HasColumnType("bigint");

                    b.Property<long>("VolumeTotal")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TypeId", "PackageDate");

                    b.ToTable("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
